//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.order_lines = new HashSet<order_lines>();
        }
    
        public int id { get; set; }
        public int clientId { get; set; }
        public Nullable<int> courierId { get; set; }
        public decimal final_price { get; set; }
        public string address_del { get; set; }
        public decimal weight { get; set; }
        public Nullable<System.DateTimeOffset> ordertime { get; set; }
        public Nullable<System.DateTimeOffset> deliverytime { get; set; }
        public int delstatusId { get; set; }
        public string comment { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual couriers couriers { get; set; }
        public virtual DelStatus DelStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_lines> order_lines { get; set; }
    }
}
