//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPizzaDeliveryContext : DbContext
    {
        public MyPizzaDeliveryContext()
            : base("name=MyPizzaDeliveryContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<couriers> couriers { get; set; }
        public virtual DbSet<DelStatus> DelStatus { get; set; }
        public virtual DbSet<ingredients> ingredients { get; set; }
        public virtual DbSet<managers> managers { get; set; }
        public virtual DbSet<order_lines> order_lines { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<pizza> pizza { get; set; }
        public virtual DbSet<pizza_sizes> pizza_sizes { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
